# print("number of letters in your name: " + str(len(input("Enter your name\n"))))
# print(3 * 3 + 3 / 3 -3)  
# print((3 * 3) / 3 + (3 - 3))
print ("welcome to the tip calculator ")
bill = (float(input("How much is the bill? " )))
tip = (float(input("How much would you like to tip 10 12 15? " )))
split = (int(input("How many people will split the bill? " )))
total = (float(bill + (100 / tip)))
final = (float(total / split))
your_cost = round(final , 2)
print (f"your total comes out to: ${your_cost}")
